controller_list:
  - name: fake_arm_controller
    joints:
      - p_joint
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - gripper_joint
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home
